<a href="https://colab.research.google.com/github/jhaabhishek873/googleColab/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy - Numerical Python
Advantages of Numpy Arrays:
  1. Allows Several Mathematical Operations
  2. Faster Operation

In [1]:
import numpy as np

List vas Numpy - Time Taken

In [2]:
from time import process_time

In [5]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0008918200000005427


Now time taken by numpy

In [6]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array +=5

end_time = process_time()

print(end_time - start_time)

0.0001261000000001289


Numpy Arrays

In [7]:
#list
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
#create 1 dim array
a = np.array([1,2,3,4])
print(a)
print(a.shape)

[1 2 3 4]
(4,)


In [9]:
#create a 2 dim array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [10]:
#change datatype
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)
print(c.shape)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
(2, 4)


Initial Placeholders in Numpy Arrays

In [12]:
# create a numpy array of Zeros
a = np.zeros((4,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
b = np.ones((4,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
c = np.full((4,4),6)
print(c)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [15]:
d = np.eye((6))
print(d)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [16]:
# creating random array --> by default it will gives value between 0-1
a = np.random.random((4,5))
print(a)

[[0.7624496  0.4099496  0.60019223 0.26580887 0.57955071]
 [0.67105671 0.91248958 0.46630375 0.26347617 0.86124685]
 [0.7974088  0.77873067 0.32677316 0.61711933 0.5364452 ]
 [0.77382003 0.56430829 0.14493912 0.48180627 0.75227348]]


In [17]:
b = np.random.randint(10,45,(5,6))
print(b)

[[23 30 38 28 12 44]
 [25 34 37 24 43 22]
 [32 38 33 12 19 40]
 [41 14 44 24 22 26]
 [11 31 31 17 38 18]]


In [19]:
# Array of evenly sapced values --> specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [22]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,3)
print(e)

[10 13 16 19 22 25 28]


In [24]:
# converting a list into numpy array
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a Numpy Array

In [25]:
c = np.random.randint(10,90,(5,5))
print(c)

[[21 66 16 15 56]
 [83 56 16 73 20]
 [63 34 64 27 15]
 [39 77 53 57 89]
 [21 14 48 14 37]]


In [26]:
print(c.shape)

(5, 5)


In [27]:
print(c.ndim)

2


In [28]:
print(c.size)

25


In [29]:
print(c.dtype)

int64


Mathematical operations on a Np array

In [30]:
list1 = [1,2,3,4,5]
list2 = [7,8,9,10,6]

print(list1 + list2)

[1, 2, 3, 4, 5, 7, 8, 9, 10, 6]


In [31]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[7 7 4]
 [8 7 1]
 [6 9 9]]
[[13 17 10]
 [13 19 15]
 [10 16 15]]


In [32]:
print(a+b)

[[20 24 14]
 [21 26 16]
 [16 25 24]]


In [33]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[20 24 14]
 [21 26 16]
 [16 25 24]]
[[ -6 -10  -6]
 [ -5 -12 -14]
 [ -4  -7  -6]]
[[ 91 119  40]
 [104 133  15]
 [ 60 144 135]]
[[0.53846154 0.41176471 0.4       ]
 [0.61538462 0.36842105 0.06666667]
 [0.6        0.5625     0.6       ]]


In [34]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[20 24 14]
 [21 26 16]
 [16 25 24]]
[[ -6 -10  -6]
 [ -5 -12 -14]
 [ -4  -7  -6]]
[[ 91 119  40]
 [104 133  15]
 [ 60 144 135]]
[[0.53846154 0.41176471 0.4       ]
 [0.61538462 0.36842105 0.06666667]
 [0.6        0.5625     0.6       ]]


Array Manipulation using numpy

In [35]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 3 4]
 [2 9 8]]
(2, 3)


In [36]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[2 2]
 [3 9]
 [4 8]]
(3, 2)


In [37]:
#reshaping
b = array.reshape(3,2)
print(b)
print(b.shape)

[[2 3]
 [4 2]
 [9 8]]
(3, 2)
